fix: first use volces.com to install flashinfer_python to fix confilct INFO: pip is looking at multiple versions of flashinfer-python to determine which version is compatible with other requirements. This could take a while. ERROR: Cannot install sglang and sglang[srt]==0.4.9.post3 because these package versions have conflicting dependencies.
The conflict is caused by:
    sglang[srt] 0.4.9.post3 depends on torch==2.7.1; extra == "srt"
    flashinfer-python 0.2.7.post1 depends on torch
    flashinfer-python 0.2.7.post1 depends on torch==2.8.*

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts